name: Terraform apply

on:
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: 1

jobs:
  terraform-apply:
    name: terraform apply
    runs-on: ubuntu-latest
    outputs:
      public_ip: ${{ steps.save-ip.outputs.public_ip }}

    env:
      TF_VAR_create_key_pair: true
      TF_VAR_key_name: "tf-mk8s-vm-key"
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.13.3'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform apply (auto-approve)
        id: tfapply
        run: terraform apply -input=false -auto-approve

      - name: Get public IP and save as output
        id: save-ip
        run: echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
