name: Terraform apply + deploy k8s manifests

on:
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: 1

jobs:
  terraform-apply:
    name: terraform apply
    runs-on: ubuntu-latest
    outputs:
      public_ip: ${{ steps.save-ip.outputs.public_ip }}

    env:
      TF_VAR_create_key_pair: true
      TF_VAR_key_name: "tf-mk8s-vm-key"
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.4.6'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform apply (auto-approve)
        id: tfapply
        run: terraform apply -input=false -auto-approve

      - name: Get public IP and save as output
        id: save-ip
        run: echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

  deploy-k8s:
    name: copy manifests & apply on instance
    runs-on: ubuntu-latest
    needs: terraform-apply
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download public IP from previous job
        run: echo "Instance IP is ${{ needs.terraform-apply.outputs.public_ip }}"

      - name: Prepare k8s manifests
        run: ls -la k8s || true

      - name: Copy k8s manifests to the instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ needs.terraform-apply.outputs.public_ip }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "k8s/*"
          target: "/home/ubuntu/k8s/"

      - name: Apply k8s manifests remotely (microk8s)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ needs.terraform-apply.outputs.public_ip }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo microk8s kubectl apply -f /home/ubuntu/k8s/
            sudo microk8s kubectl rollout status deploy/nginx-deployment -n app --timeout=120s || true