name: Terraform destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm destroy'
        required: true
        default: 'no'

env:
  TF_IN_AUTOMATION: 1

jobs:
  terraform-destroy:
    if: ${{ github.event.inputs.confirm == 'yes' }}
    name: Terraform destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.13.3'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform destroy (auto-approve)
        run: terraform destroy -input=false -auto-approve